//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::bet::Entity as Bet;
pub use super::bets::Entity as Bets;
pub use super::participants::Entity as Participants;
pub use super::player::Entity as Player;
